# ------------------------------------
# LevelApp-Store - Peticiones HTTP :)
# ------------------------------------

### RAIZ
GET http://127.0.0.1:3000/ HTTP/1.1


# ----------------
# JUEGOS
# ----------------

### GET ALL - Trae todos los juegos.
GET http://127.0.0.1:3000/juegos HTTP/1.1


### GET BY ID - Trae un juego por id.
GET http://127.0.0.1:3000/juegos/23 HTTP/1.1


### POST - Crear un juego nuevo.
POST http://127.0.0.1:3000/juegos HTTP/1.1
Content-Type: application/json

{
    "Nombre": "Metal slug",
    "Precio": 7900,
    "Stock": 3,
    "IdCategoria": 3
}

### PATCH - Actualizar precio y stock de un juego.
PATCH http://127.0.0.1:3000/juegos/23 HTTP/1.1
Content-Type: application/json

{
    "Precio": 2000,
    "Stock": 5
}

#### PUT - Actualizar registro completo de un juego
PUT http://127.0.0.1:3000/juegos/20 HTTP/1.1
Content-Type: application/json

{
    "Nombre": "Retro World Modificado",
    "Precio": 17000.00,
    "Stock": 26,
    "IdCategoria": 4
}


### DELETE - Eliminar un juego por id.
DELETE http://127.0.0.1:3000/juegos/24 HTTP/1.1


# ----------------
# COMPRAS
# ----------------

### GET ALL - Trae todas las compras.
GET http://127.0.0.1:3000/compras HTTP/1.1


### GET BY ID - Trae las compras de un juego por id.
GET http://127.0.0.1:3000/compras/1 HTTP/1.1